'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CategoriaA
    Public Property id_categoria As Integer
    Public Property id_actividad As Integer
    Public Property descripcion As String
    Public Property detalle As String
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Actividad As Actividad

End Class
