'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tipo_Concepto
    Public Property id_tipoConcepto As Integer
    Public Property descripcion As String
    Public Property estado_R_NRm As Nullable(Of Boolean)
    Public Property estadobaja As Nullable(Of Boolean)

    Public Overridable Property Concepto As ICollection(Of Concepto) = New HashSet(Of Concepto)

End Class
