'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property idUser As Integer
    Public Property dni As Integer
    Public Property contraseña As String
    Public Property estado As Nullable(Of Boolean)
    Public Property idRol As Nullable(Of Integer)

    Public Overridable Property Rol As Rol

End Class
